/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Catalogos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author office depot
 */
public class frmCatalogoProveedor extends javax.swing.JInternalFrame {
       Connection conexion;
       boolean modifica=false;
    /**
     * Creates new form frmCatalogoProveedor
     */
    public frmCatalogoProveedor() {
        initComponents();
        setClosable(true);
        setMaximizable(true);
         inicializaBaseDeDatos();
         llenaTablaProveedor();
    }
public void inicializaBaseDeDatos(){
        try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            conexion = DriverManager.
                    getConnection("jdbc:mysql://"
                    + "localhost/farmacia","root","");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public void llenaTablaProveedor(){
        try{            
            DefaultTableModel model = new DefaultTableModel();
            tablaProveedor.setModel(model);
            
            PreparedStatement consulta = conexion.prepareStatement(""
                    + "SELECT * FROM proveedor WHERE status=1");                  
            ResultSet rs = consulta.executeQuery();
            
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();            
            for(int i = 1; i <= cantidadColumnas; i++){
                model.addColumn(rsMd.getColumnLabel(i));
            }
            
            while(rs.next()){
                Object[] fila = new Object[cantidadColumnas];
                for(int j=1; j <= cantidadColumnas; j++){
                    fila[j-1] = rs.getObject(j);
                }                
                
                model.addRow(fila);
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
                    
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApellido_paterno = new javax.swing.JTextField();
        txtApellido_materno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Sistema de proveedores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 27, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 70, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Proveedor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 107, -1, -1));

        txtId.setText("Nuevo");
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 67, 74, -1));
        getContentPane().add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 104, 204, -1));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 67, 65, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.png"))); // NOI18N
        btnEliminar.setToolTipText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 67, -1, 57));

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modificar.png"))); // NOI18N
        btnModificar.setToolTipText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 67, -1, 57));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 786, 10));

        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Buscar proveedor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 373, -1, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 370, 190, -1));

        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProveedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 424, 766, 215));

        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Empresa:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 240, -1, -1));

        txtEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 237, 204, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Apellido paterno:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 153, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Apellido materno:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 202, -1, -1));
        getContentPane().add(txtApellido_paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 150, 204, -1));
        getContentPane().add(txtApellido_materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 199, 202, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Fondo-color-verde-688051.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre_proveedor = txtProveedor.getText();
        String empresa = txtEmpresa.getText();
        String apellido_paterno = txtApellido_paterno.getText();
        String apellido_materno = txtApellido_materno.getText();
        //String producto = txtProducto.getText();
        //String cantidad = txtCantidad.getText();
        //String precio_unitario = txtPrecio_unitario.getText();
        //String total = txtTotal.getText();
        int id=0;
         if(modifica){
            id=Integer.parseInt(txtId.getText());
        }
        if (nombre_proveedor.length() == 0 || empresa.length() == 0 
               || apellido_paterno.length() == 0  || apellido_materno.length() == 0 )
        {
                JOptionPane.showMessageDialog(null, "Debes llenar todos los campos para registrar.");
                return;
        }
        try{            
           PreparedStatement consulta;
            if(modifica){
            consulta=conexion.prepareStatement(""+"UPDATE  proveedor SET nombre_proveedor=?,apellido_paterno=?,apellido_materno=?,empresa=? WHERE id_proveedor=?");
            consulta.setString(1, nombre_proveedor);
            consulta.setString(2, apellido_paterno);
            consulta.setString(3, apellido_materno);
            consulta.setString(4, empresa);
           // consulta.setString(2, producto);
            //consulta.setString(3, cantidad);
            //consulta.setString(4, precio_unitario);
            //consulta.setString(5, total);
            consulta.setInt(5,id);
            }else{
            consulta = conexion.prepareStatement(""
                    + "INSERT INTO proveedor(nombre_proveedor, apellido_paterno,apellido_materno, empresa) VALUES (?,?,?,?)");                  
           consulta.setString(1, nombre_proveedor);
           consulta.setString(2, apellido_paterno);
           consulta.setString(3, apellido_materno);
           consulta.setString(4, empresa);
          // consulta.setString(2, producto);
           //consulta.setString(3, cantidad);
           //consulta.setString(4, precio_unitario);
           //consulta.setString(5, total);  
              JOptionPane.showMessageDialog(null, "ahora registre los productos en Catalogo-->Medicamentos");
            }
           
           consulta.executeUpdate();
           
           llenaTablaProveedor();
           
           limpiaCampos();
           
        }catch(Exception e){
            e.printStackTrace();       
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int id = (int) tablaProveedor.getValueAt(tablaProveedor.getSelectedRow(), 0);
           String nombre_proveedor= (String) tablaProveedor.getValueAt(tablaProveedor.getSelectedRow(), 1);  // 1 es la columna 1=nombre
           String apellido_paterno= (String) tablaProveedor.getValueAt(tablaProveedor.getSelectedRow(), 2); //2=apellido_paterno
           String apellido_materno= (String) tablaProveedor.getValueAt(tablaProveedor.getSelectedRow(), 3);
           String empresa= (String) tablaProveedor.getValueAt(tablaProveedor.getSelectedRow(), 4);
           //String producto= (String) tablaProveedor.getValueAt(tablaProveedor.getSelectedRow(), 2); //2=apellido_paterno
           //String cantidad= (String) tablaProveedor.getValueAt(tablaProveedor.getSelectedRow(), 3); 
           //String precio_unitario= (String) tablaProveedor.getValueAt(tablaProveedor.getSelectedRow(), 4); 
           //String total= (String) tablaProveedor.getValueAt(tablaProveedor.getSelectedRow(), 5); 
           // int telefono= (int) tablaUsuario.getValueAt(tablaUsuario.getSelectedRow(), 4);
           // txtTelefono.setText(""+telefono);
        txtId.setText("" + id);
        txtProveedor.setText(nombre_proveedor);
        txtApellido_paterno.setText(apellido_paterno);   
        txtApellido_materno.setText(apellido_materno);
        txtEmpresa.setText(empresa);
        //txtProducto.setText(producto);
        //txtCantidad.setText(cantidad);
        //txtPrecio_unitario.setText(precio_unitario);
        //txtTotal.setText(total);
        modifica=true;// TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
 int id =(int) tablaProveedor.getValueAt(tablaProveedor.getSelectedRow(), 0);
    
        try{            
           PreparedStatement consulta = conexion.prepareStatement(""
                    + "UPDATE proveedor SET status=2 WHERE id_proveedor=?");                  
           consulta.setInt(1, id);   
           
           
           consulta.executeUpdate();
           
           llenaTablaProveedor();
           limpiaCampos();
           // txtId.setText("Nuevo");
        }catch(Exception e){
            e.printStackTrace();       
        }                  // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
try{
        DefaultTableModel model = new DefaultTableModel();
        tablaProveedor.setModel(model);
       /* PreparedStatement consulta = conexion.prepareStatement(""
                + "SELECT * FROM usuarios WHERE status=1 AND nombre LIKE ?");     //LIKE --> sirve para comparar cadeenas
                                                                                     //        WHERE campo LIKE '%caracter%'
        consulta.setString(1, "%"+txtBuscar.getText()+"%");*/
        
        PreparedStatement consulta = conexion.prepareStatement(""
                + "SELECT * FROM proveedor WHERE status=1 AND nombre_proveedor LIKE ?");  
        consulta.setString(1, "%"+txtBuscar.getText()+"%");
        ResultSet rs = consulta.executeQuery();                                
        ResultSetMetaData rsMd = rs.getMetaData();
        int cantidadColumnas = rsMd.getColumnCount();
        for (int i=1; i<= cantidadColumnas; i++){
            model.addColumn(rsMd.getColumnLabel(i));
        }
    while (rs.next()){
        Object[] fila = new Object[cantidadColumnas];
        for (int j =1; j<= cantidadColumnas; j++){
            fila[j-1]= rs.getObject(j);
        }
        model.addRow(fila);
    }
    
    
}catch(Exception e){
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpresaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    public void limpiaCampos(){
         txtId.setText("Nuevo");
        txtProveedor.setText("");
        txtApellido_paterno.setText("");
        txtApellido_materno.setText("");
        txtEmpresa.setText("");
        //txtProducto.setText("");
        //txtCantidad.setText("");
        //txtPrecio_unitario.setText("");
        //txtTotal.setText("");
        modifica=false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCatalogoProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCatalogoProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaProveedor;
    private javax.swing.JTextField txtApellido_materno;
    private javax.swing.JTextField txtApellido_paterno;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtProveedor;
    // End of variables declaration//GEN-END:variables
}
