/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package puntoventa;

import Catalogos.frmCatalogoCliente;
import Catalogos.frmCatalogoEntrada;

import Catalogos.frmCatalogoMedicamentos;
import Catalogos.frmCatalogoProveedor;
import Catalogos.frmCatalogoSalida;
import informacion.frmAcercaDe;
import javax.swing.JFrame;

import usuario.frmCatalogoUsuario;
import ventas.frmRealizarVenta;

/**
 *
 * @author office depot
 */
public class MDIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MDIPrincipal
     */
    public MDIPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCatalogo = new javax.swing.JMenu();
        itemUsuario = new javax.swing.JMenuItem();
        itemCliente = new javax.swing.JMenuItem();
        itemMedicamentos = new javax.swing.JMenuItem();
        itemProveedor = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        itemVenta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 204, 255));
        desktopPane.setLayout(null);
        desktopPane.add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sistem.png"))); // NOI18N
        desktopPane.add(jLabel1);
        jLabel1.setBounds(120, 30, 470, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cruz-verde.png"))); // NOI18N
        desktopPane.add(jLabel3);
        jLabel3.setBounds(10, 10, 120, 117);

        menuCatalogo.setText("Catalogo");

        itemUsuario.setText("Usuarios");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        menuCatalogo.add(itemUsuario);

        itemCliente.setText("Clientes");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        menuCatalogo.add(itemCliente);

        itemMedicamentos.setText("Medicamentos");
        itemMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMedicamentosActionPerformed(evt);
            }
        });
        menuCatalogo.add(itemMedicamentos);

        itemProveedor.setText("Proveedor");
        itemProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProveedorActionPerformed(evt);
            }
        });
        menuCatalogo.add(itemProveedor);

        jMenuBar1.add(menuCatalogo);

        menuVentas.setText("Ventas");

        itemVenta.setText("Realizar venta");
        itemVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVentaActionPerformed(evt);
            }
        });
        menuVentas.add(itemVenta);

        jMenuBar1.add(menuVentas);

        jMenu1.setText("Bodega");

        jMenuItem2.setText("Entradas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salidas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        menuAyuda.setText("Ayuda");
        menuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyudaActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Informacion del sistema");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAyuda.add(jMenuItem1);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
     frmCatalogoUsuario CatalogoUsuario = new frmCatalogoUsuario();
     desktopPane.add(CatalogoUsuario);   
     CatalogoUsuario.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void menuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyudaActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_menuAyudaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmAcercaDe AcercaDe = new frmAcercaDe();
        desktopPane.add(AcercaDe);  
        AcercaDe.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMedicamentosActionPerformed
         frmCatalogoMedicamentos CatalogoMedicamentos = new frmCatalogoMedicamentos();
        desktopPane.add(CatalogoMedicamentos);   
        CatalogoMedicamentos.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_itemMedicamentosActionPerformed

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
     frmCatalogoCliente CatalogoCliente = new frmCatalogoCliente();
     desktopPane.add(CatalogoCliente);   
     CatalogoCliente.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_itemClienteActionPerformed

    private void itemProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProveedorActionPerformed
     frmCatalogoProveedor CatalogoProveedor = new frmCatalogoProveedor();
     desktopPane.add(CatalogoProveedor);   
     CatalogoProveedor.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_itemProveedorActionPerformed

    private void itemVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentaActionPerformed
        frmRealizarVenta RealizarVenta = new frmRealizarVenta();
     desktopPane.add(RealizarVenta);   
     RealizarVenta.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_itemVentaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frmCatalogoEntrada CatalogoEntrada = new frmCatalogoEntrada();
     desktopPane.add(CatalogoEntrada);   
     CatalogoEntrada.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      frmCatalogoSalida CatalogoSalida = new frmCatalogoSalida();
     desktopPane.add(CatalogoSalida);   
     CatalogoSalida.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JMenuItem itemMedicamentos;
    private javax.swing.JMenuItem itemProveedor;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JMenuItem itemVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCatalogo;
    private javax.swing.JMenu menuVentas;
    // End of variables declaration//GEN-END:variables
}
